dataset:
  type: DefaultDataset
  path: Iris.csv
  delimeter: ","
  id_column: True
  column_names: True

explanation:
  method: lime

input:
  class_names: ['setosa', 'versicolor', 'virginica']
  input_type: np.array
  feature_names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
  function: predict_proba
  values: [7.0,3.2,4.7,1.4]

model:
  module: sklearn
  model_obj: ensemble.RandomForestClassifier
  weights: checkpoints/rf/sklearn_iris.pkl

output:
  name: lime_rf_iris
  path: results