app:
  mode: "global"           # Режим работы приложения: "global" для глобального объяснения, "local" для локального.
  interactive: false       # Запускать ли приложение в интерактивном режиме (для отсутствия обязательных аргументов).
  output_format: "console" # Формат вывода результатов: "console", "json", "html", etc.

logging:
  level: "INFO"            # Уровень логирования: DEBUG, INFO, WARNING, ERROR.
  file: ""                 # Путь к файлу логов (если оставить пустым, вывод будет в консоль).

model:
  type: "pt"                               # Тип модели: "pt" для PyTorch.
  weights_path: "models/my_model_weights.pt"  # Путь к файлу с весами.
  architecture:
    path: "models/my_model_arch.py"          # Путь к файлу, содержащему описание архитектуры.
    class_name: "MyModel"                    # Имя класса, определяющего архитектуру.
    init_params:                           # (Опционально) Параметры для инициализации архитектуры.
      param1: value1
      param2: value2
  additional_parameters: {}                  # Дополнительные параметры для загрузки модели (если потребуется).

dataset:
  path: "datasets/data.csv"        # Путь к CSV-файлу
  type: "csv"                      # Тип датасета: "csv"
  csv_params:                      # Специфические параметры для CSV-файлов
    delimiter: ","                 # Разделитель полей (например, запятая)
    index_col: 0                   # Номер столбца для использования в качестве индекса (можно задать null, если индексной колонки нет)
    header: 0                      # Номер строки с заголовками колонок (null, если в файле нет заголовка)
  preprocess:                      # Дополнительные параметры препроцессинга
    normalize: true                # Пример параметра для нормализации данных
    resize: 256                    # Например, для изображений — целевой размер
    additional_steps: []           # Список дополнительных шагов препроцессинга

explainer:
  type: "lime"                # Выбранный метод объяснения: "lime", "shap" и т.д.
  parameters:
    num_features: 10          # Количество признаков для отображения в отчёте объяснения.
    num_samples: 5000         # Количество сэмплов для генерации объяснения (например, для LIME).
    additional_params: {}     # Дополнительные параметры, специфичные для выбранного метода.

local:
  input_path: "datasets/sample_input.json" # Путь к конкретному примеру входных данных для локального объяснения.