explanation:
  method: lime

input:
  class_names: ['Approved', 'Rejected']
  input_type: np.array
  feature_names: ['Income', 'Age', 'Loan_Amount', 'Debt', 'Dependents', 'Credit_History_Good', 'Employment_Status_Unemployed']
  function: predict_proba
  values: [29258, 50, 298.05, 5720.3, 3, True, False]

model:
  module: sklearn
  model_obj: ensemble.RandomForestClassifier
  weights: checkpoints/rf/sklearn_credit.pkl

output:
  name: lime_rf_credit
  path: results