app:
  mode: local
  output_format: console

logging:
  level: INFO

model:
  type: keras
  path: weights/mnist_mlp.keras

dataset:
  type: builtin
  name: mnist
  max_samples: 100

explainer:
  type: shap
  num_features: 10

local:
  dataset:
    type: builtin
    name: mnist
    only_x: true
    max_samples: 1
