app:
  mode: local
  output_format: console

logging:
  level: INFO

model:
  type: keras
  path: weights/house_lin_reg.keras

dataset:
  type: csv
  path: datasets/house_pricing_dataset.csv
  delimiter: ","
  header: 0
  only_x: true

explainer:
  type: shap
  num_features: 15

local:
  dataset:
    type: csv
    path: datasets/house_sample.csv
    header: null
    only_x: true
