app:
  mode: global
  output_format: console

logging:
  level: INFO

model:
  type: keras
  path: weights/house_lin_reg.keras

dataset:
  type: csv
  path: datasets/house_pricing_dataset.csv
  delimiter: ","
  header: 0
  only_x: true

explainer:
  type: lime
  num_features: 199
  num_samples: 5000
  global_samples: 10
