app:
  mode: global
  output_format: console

logging:
  level: INFO

model:
  type: sklearn
  path: weights/iris_random_forest.pkl

dataset:
  type: builtin
  name: iris

explainer:
  type: shap
  num_features: 10
