app:
  mode: local
  output_format: console

logging:
  level: INFO

model:
  type: sklearn
  path: weights/alzheimer_log_reg.pkl

dataset:
  type: csv
  path: datasets/alzheimers_disease_data.csv
  delimiter: ","
  header: 0

explainer:
  type: lime
  num_features: 20
  num_samples: 5000

local:
  dataset:
    type: csv
    path: datasets/alzheimer_sample.csv
    only_x: true
