app:
  mode: local
  output_format: console

logging:
  level: INFO

model:
  type: sklearn
  path: weights/iris_random_forest.pkl

dataset:
  type: csv
  path: datasets/Iris.csv
  delimiter: ","
  header: 0
  index_col: Id

explainer:
  type: lime
  num_features: 10
  num_samples: 5000

local:
  dataset:
    type: csv
    path: datasets/iris_sample_input.csv
    only_x: true
