app:
  mode: global
  output_format: html

logging:
  level: INFO

model:
  type: sklearn
  path: weights/ts_italy_mlp.pkl

dataset:
  type: timeseries
  path: datasets/ts_italy_power_train.npy
  n_timesteps: 24

explainer:
  type: shap
  num_features: 6
